name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - uses: actions/checkout@v2
    - name: Build the Docker image
      with:
        context: ./models/Dockerfile
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/train_image:latest
        push: true

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
