name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # - name: Build the Docker image
    #   uses: actions/checkout@v1
    #   with:
    #     context: ./models/Dockerfile
    #     tags: ${{ secrets.DOCKER_HUB_USERNAME }}/train_image:latest
    #     push: true
    #   run: docker build . --file ./models/Dockerfile --tag train_image:$(date +%s)

    # - name: Image digest
    #   uses: actions/checkout@v1
    #   run: echo ${{ steps.docker_build.outputs.digest }}
